export const FETCH_QUIZ_SETTING_REQUEST = "FETCH_QUIZ_SETTING_REQUEST";
export const FETCH_QUIZ_SETTING_SUCCESS = "FETCH_QUIZ_SETTING_SUCCESS";
export const FETCH_QUIZ_SETTING_FAILURE = "FETCH_QUIZ_SETTING_FAILURE";
